### ISSUE TITLE
When fileSizeLimitBytes is reached, RollingFile sink should still roll logs in a single file

### ISSUE THREAD

**Issue by derFunk** [serilog/serilog-sinks-rollingfile#38] opened 2016-11-11 17:31 UTC
Don't stop logging after the max file size has been reached, and the log file count is limited to 1 (e.g. when using date based rolling). Just clear the file and start new again.

Currently, if `fileSizeLimitBytes` is reached, Serilog simply stops logging, which is not acceptable (See https://github.com/serilog/serilog-sinks-file/blob/ea75e90815fb12075fa41040100806e791acc99d/src/Serilog.Sinks.File/Sinks/File/FileSink.cs#L83-L87).

**Comment by nblumhardt** [comment] 2016-11-18 05:25
Hi Andreas, thanks for the note. This one's a dupe of #27, but sounds like it needs some more attention.

From the earlier ticket:

> (This) behavior's by design. The size limit is not for rolling the file contents, but to prevent runaway disk usage if for example the app gets stuck in an infinite loop.
> 
> When such a thing occurs (logging in an infinite loop) the log file will be useless in diagnosing why it happened if the only things in the log file are the events generated in the loop. By dropping the overflowing events but keeping the earlier ones, the history leading up to the problem is retained.

I would guess that your scenario might be a bit better described by #26 (static filenames) - do you think this ticket can be closed in favour of continuing the discussion there?

**Comment by nblumhardt** [comment] 2016-11-25 03:54
Closing in favour of #26.

**Closed as completed by nblumhardt** 2016-11-25 03:54 UTC

**Comment by nblumhardt** [comment] 2017-10-17 03:56
Just a quick note, rolling on file size is now implemented in the -dev version of _Serilog.Sinks.File_. [The README over there](https://github.com/serilog/serilog-sinks-file) has all of the details. HTH!
